apiVersion: apps/v1 
kind: Deployment
metadata:
  name: flink-deployment-master
  labels:
    app: flink-app-master
spec:
  selector:
    matchLabels:
      app: flink-app-master
      tier: flink-deployment-master
  replicas: 1
  template:
    metadata:
      labels:
        app: flink-app-master
        tier: flink-deployment-master
    spec:
      containers:
      - name: flink-image
        image: sameerbhat/flinkraw
        ports:
        - containerPort: 8081